---
title: "Lab 00 - Hello IDS!"
author: "Scarlett Guang"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Scarlett", "Liam", "Matucus", 
           "Linual", "member 4"),
  github_username = c("username", "username 1", "username 2", 
                      "username 3", "username 4"), 
  colour = c("blue", "red", "yellow", 
             "green", "colour 4"),
  hobby = c("Hop", "theatre", "squash", 
            "golf", "hobby 4"),
  favourite_number = c(33, 2, 324, 5, NA)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

Ignors team members' hobbies. Focuses on favourite numbers and colors. 


